### ISSUE TITLE
Refresh: Pagination showing at least a number of button when at sides' ends

### ISSUE THREAD

**Issue by khanghugo** [jambonz/jambonz-webapp#100]
Right now, when selected page is 1, it will show only 2, no 3 or 4. Hence, the number of shown buttons will move around and it can get annoying for that first few. I did really try to implement this with just boolean but the prettifier does not like what I do so I guess we can do something a bit more imperative for that.

**Comment by kitajchuk** [comment]
@khanghugo Not a bad call. Currently it functions quite similar to the old webapp but it could be nice to make it jump around less on the user 🤔

**Comment by kitajchuk** [comment]
@khanghugo Another enhancement issue could be to support the query parameters in the URL address such that you could technically share a page of results and it would do an initial fetch with all the correct filters and pagination criteria 🤔
