### ISSUE TITLE
Bug: Phone numbers can be assigned an application that does not belong to the same account that the number/carrier belongs to

### ISSUE THREAD

**Issue by kitajchuk** [jambonz/jambonz-webapp#104]
You should only be able to assign an application to a phone number where the application belongs to the same account that the phone number/carrier belongs to (with the exception that the carrier can be associated to the account’s parent service provider).

Bug: currently you can assign a phone number to an application that does not belong to the same account that the phone number/carrier belongs to via the mass edit function from the phone numbers list view.

Proposed solution: provide an account filter to the phone numbers list view and only further provide the mass edit UI if an account has been selected to filter the list. This means we would need to maintain a filtered set of phone numbers as our primary render list and the application selector would need to filter applications by the selected account.

**Comment by xquanluu** [comment]
Start working on this

**Comment by kitajchuk** [comment]
@xquanluu I was meaning to document some implementation details for this I just hadn't gotten around to it. We essentially have examples of exactly how to make the changes we need to see here already on the carriers index so I'll document the necessary changes here so that we keep things DRY and follow like patterns. Hopefully you're not too far in to anything else or maybe you already stumbled on these pre-existing patterns.

First you'll want to use the `AccountFilter` component like we do on other views. Here's the example from the carriers index:
https://github.com/jambonz/jambonz-webapp/blob/refresh/src/containers/internal/views/carriers/index.tsx#L110-L115

This phone numbers view already has a fuzzy filter so it will need 2 layers of filter now: first by `accountSid` and then by fuzzy search filter. We have already done this on the carrier view as well so the implementation here should be the same:
https://github.com/jambonz/jambonz-webapp/blob/refresh/src/containers/internal/views/carriers/index.tsx#L34-L47

With that in place all you'll need to do is conditionally render this first list item so long as the `accountSid` is set:
https://github.com/jambonz/jambonz-webapp/blob/refresh/src/containers/internal/views/phone-numbers/index.tsx#L120-L169

I think that's pretty much it. This should be an easy one since we just need to do the above. If I'm missing anything let me know, but I'm pretty sure this is it.

**Comment by khanghugo** [comment]
Hmmm, this was what I was talking about in the PR thread too, I believe. The old webapp does behave this way so I did have it in parity. Glad to see it gets clarified.
