### ISSUE TITLE
Feature: Support custom endpoints for Azure speech

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#119]
As background, currently when we collect speech credentials for Microsoft/Azure we collect a region and a subscription key.  On the back end, we use this information by connecting to an Azure URL/endpoint for that region when we want to use the credentials to do TTS or STT.

Azure also has the ability for a customer to create a [custom neural voice ](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/custom-neural-voice) for TTS, and/or to create a [custom speech model](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/custom-speech-overview) for STT, and we would like to support these.

To do so, the Add/Edit speech credentials panel should be enhanced in the following way:

When vendor is 'Microsoft', add the following new UI controls to the bottom of the panel (above the Cancel/Save buttons)

- a checkbox labeled: "Use a custom voice"
- an input field labeled: Custom voice endpoint

- a checkbox labeled "Use a custom speech model"
- an input field labeled: Custom speech endpoint

Note that the input fields should only be enabled when the corresponding checkbox is checked.

These fields should then be provided in the POST/PUT to the back end with the following property names in the JSON payload of the request: use_custom_tts (0 or 1), custom_tts_endpoint, use_custom_stt (0 or 1), custom_stt_endpoint.

For backwards compatibility, the webapp should be prepared to receive a payload from a GET which does not contain any of these properties, and in that case the checkboxes should be left unchecked and the input field empty.

This feature needs to be done on the legacy branch (first) and then the main branch.

**Comment by davehorton** [comment]
there is a required change in jambonz-api-server for this.  I will make this now

**Comment by davehorton** [comment]
this has been committed on the latest main branch of jambonz-api-server, so test with that.  For initial testing, you can enter any thing in the custom endpoint field, just make sure it is saved and retrieved properly.

**Comment by xquanluu** [comment]
Start working for legacy branch

**Comment by xquanluu** [comment]
Start working for main branch

**Comment by kitajchuk** [comment]
@xquanluu Here's some notes for when you get to implementing this on the new app.

For the requirement of only showing the new fields when their corresponding checkboxes are enabled you can use our custom `Checkzone` component. It's used a lot in the application so there's no shortage of examples. The typical model is to have a local state var for the "initial checked state" of the component and this is passed as a prop. For all our forms we handle initial state setting in an effect and this is where you would check for the presence of the optional fields and set the true/false state of the initial checked prop for each zone. You can see here in the speech form we have examples of setting the checked state for TTS/STT so the model is the same when using Checkzone's:

https://github.com/jambonz/jambonz-webapp/blob/76857c0a4b321b98bb2ab1a70fc818be19b4ec8e/src/containers/internal/views/speech-services/form.tsx#L148-L158

But also for a Checkzone example (as I mentioned there are many in the app code) you can see how we create the state var on the settings form here:

https://github.com/jambonz/jambonz-webapp/blob/76857c0a4b321b98bb2ab1a70fc818be19b4ec8e/src/containers/internal/views/settings/index.tsx#L34

And then how we set the initial value of true/false here:

https://github.com/jambonz/jambonz-webapp/blob/76857c0a4b321b98bb2ab1a70fc818be19b4ec8e/src/containers/internal/views/settings/index.tsx#L121-L128

And where we render the Checkzone:

https://github.com/jambonz/jambonz-webapp/blob/76857c0a4b321b98bb2ab1a70fc818be19b4ec8e/src/containers/internal/views/settings/index.tsx#L157-L174

You can play around in the app and see all the various places we use the Checkzone component. There is also a prop called `hidden` which tells whether the content inside of the Checkzone should be hidden when it is not checked. I believe the only place where we don't hide the content while it's not checked is in the settings form so I would say here we will want to use this hidden prop like we do in most cases. Here's some screenshots of what it looks like:

<img width="606" alt="Screen Shot 2022-09-27 at 7 21 15 AM" src="https://user-images.githubusercontent.com/438711/192552532-b5e5d764-8dec-4a40-a924-f7d9c2a68ac1.png">

<img width="588" alt="Screen Shot 2022-09-27 at 7 21 24 AM" src="https://user-images.githubusercontent.com/438711/192552539-b9a8bad4-6688-4880-a2aa-1078d5ab169f.png">

**Comment by kitajchuk** [comment]
@davehorton I was playing around with this and it looks like the API doesn't allow you to update the values for these new fields. So when I post if I send `null` for an endpoint and `0` for the checked value the backend doesn't save these values and I am left with still having the previous values of some endpoint string and a `1`...

**Comment by davehorton** [comment]
hmm, are you testing with the latest (from this morning) jambonz-api-server main branch?

**Comment by kitajchuk** [comment]
> hmm, are you testing with the latest (from this morning) jambonz-api-server main branch?

Yes I just pulled maybe like 30 minutes ago...

**Comment by davehorton** [comment]
ah ok that is a bug on the back-end, I will fix.

Also, the obfuscation of the key is causing an issue with an "update".  On the legacy branch at least, the obfuscated api_key is being sent, which then gets in the database and is invalid.  I guess I will also need a change on the back end to retrieve the existing (valid) key from the db and use that instead of anything sent through from the client?  Otherwise I can't think how to allow someone to change the region (which should be a valid thing to do)

I think the client should *not* send the api_key (for ms, or the similarly obfuscated credentials from aws or google) but *should* be able to send a new/idfferent region, different settings for use_for_tts/use_for_stt, as well as the new custom endpoint fields for azure.  And the back end will then dip the db to retrieve the sensitive credentials and insert that for encryption.

Thoughts?

**Comment by kitajchuk** [comment]
> ah ok that is a bug on the back-end, I will fix.
> 
> Also, the obfuscation of the key is causing an issue with an "update". On the legacy branch at least, the obfuscated api_key is being sent, which then gets in the database and is invalid. I guess I will also need a change on the back end to retrieve the existing (valid) key from the db and use that instead of anything sent through from the client? Otherwise I can't think how to allow someone to change the region (which should be a valid thing to do)
> 
> I think the client should _not_ send the api_key (for ms, or the similarly obfuscated credentials from aws or google) but _should_ be able to send a new/idfferent region, different settings for use_for_tts/use_for_stt, as well as the new custom endpoint fields for azure. And the back end will then dip the db to retrieve the sensitive credentials and insert that for encryption.
> 
> Thoughts?

For the obfuscation stuff—the new web app just doesn't send the keys for the PUT requests. So they are only sent on the initial POST and never again:

https://github.com/jambonz/jambonz-webapp/blob/76857c0a4b321b98bb2ab1a70fc818be19b4ec8e/src/containers/internal/views/speech-services/form.tsx#L86-L135

I think it would be good to let them change the region as well as all the new values for this feature. And they can already change the use for tts/stt so that won't change.

**Comment by kitajchuk** [comment]
@davehorton Well in an attempt to validate these APIs I basically got this implemented on the new web app. I think the legacy app will need to do something similar as we have here regarding secrets in the payload in order to overcome the secret obscurity issue you're having there.

https://github.com/jambonz/jambonz-webapp/pull/122

**Comment by davehorton** [comment]
I pushed a commit on jambonz-api-server that I think fixes the problem with updates.

**Comment by davehorton** [comment]
minor change request (on both legacy and main)

Can we change the label "Custom speech endpoint" to "Custom speech endpoint Id"

**Comment by xquanluu** [comment]
> minor change request (on both legacy and main)
> 
> Can we change the label "Custom speech endpoint" to "Custom speech endpoint Id"

PRs created, please help to review
