### ISSUE TITLE
Feature: multi-user branch PR 1 - create password settings screen

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#124]
FYI, I am going to create a series of PRs that we can work against for adding the multi-user support.  These should all be worked as PRs off the `feature/multi-user` branch (ie I have checked in that branch, please branch from it and then make PRs against it, when all PRs are complete we will merge to main)

The first one is simple: to add a new panel/form that allows an admin-level user to specify the rules for creating passwords.  Eventually, only admin levels will see this; to start with since we only have admin users, the PR should just add the new panel/form.  

Looking for input on UI from @kitajchuk here) but my thought was that was we already have a "Settings" panel where this could live, except that panel has Service Provider level settings, and this is an admin-level setting.  However, maybe we extend/enhance that Settings panel to have two sections (or tabs) labeled 'Admin' and 'Service Provider'?  (In a later PR we can worry about hiding the Admin tab from a service provider user, for this PR we dont need to).

I'm assigning to @kitajchuk first for UI thoughts (and do we need an actual UI worked up in Figma, or is that overkill?).  When completed and agreed, this issue should then be assigned to @xquanluu for implementation

**Comment by kitajchuk** [comment]
> Looking for input on UI from @kitajchuk here) but my thought was that was we already have a "Settings" panel where this could live, except that panel has Service Provider level settings, and this is an admin-level setting. However, maybe we extend/enhance that Settings panel to have two sections (or tabs) labeled 'Admin' and 'Service Provider'? (In a later PR we can worry about hiding the Admin tab from a service provider user, for this PR we dont need to).

I think the tabs could work. The only other option would be to have another link in the nav for an entirely new route for Admin settings and I'm not really into that notion lol. For the tabs would we default to Admin tab in first position or Service Provider tab in first position? Note that this only matters for admins long-term as the Service Provider user role would only see the one tab for them anyway. Also note that my intention would be to place the tabs in the form section (same as Carrier form) so the API keys section would be visible no matter which tab you are on—is this okay?

**Comment by davehorton** [comment]
I would say admin in first position, then service provider.  And yes, seeing the API keys would be fine -- but maybe we relabel them to "Service Provider API Keys" to be clear?

**Comment by davehorton** [comment]
@kitajchuk  @xquanluu  I am keen to get started on this...the multi-user work needs to be the top priority now.  With the decision above, what else do we need to get Hoan started on this?

**Comment by xquanluu** [comment]
Start working on this. I will try to work with above discussion and then we can review and change like other PR we did when seeing something bad

**Comment by xquanluu** [comment]
![service_tab](https://user-images.githubusercontent.com/110280845/193229721-cb970f76-5ab9-4f1f-8218-6dbbc6dcc869.PNG)
![admin_tabs](https://user-images.githubusercontent.com/110280845/193229725-d850f6ae-88c6-4157-8465-3d650deba615.PNG)

I want to get confirmation that the settings should be like this layout.

**Comment by davehorton** [comment]
The tabs look good.  But for the admin settings, I want something easier to use than regex.  It should be simple checkboxes and a dropdown for min password length.  Here is an example -- not exactly on target since it is for generating a password vs password rules -- but look at how intuitive it is:

![image](https://user-images.githubusercontent.com/1884973/193232154-7564b483-c94d-4645-8b96-b4f112dc82da.png)

Can you come up with something like that?  e.g.

- Minimum password length (dropdown, defaulting to 8, choices from 6 to 20)
- Require at least one digit (checkbox)
- Require at least one special character: !@#$%^&*()+ (checkbox)

**Comment by xquanluu** [comment]
@davehorton yes sure, I will work on that soon.

**Comment by davehorton** [comment]
yes, maybe work on that first, actually, while we wait for @kitajchuk  to chime in on the UI

**Comment by kitajchuk** [comment]
> ![service_tab](https://user-images.githubusercontent.com/110280845/193229721-cb970f76-5ab9-4f1f-8218-6dbbc6dcc869.PNG) ![admin_tabs](https://user-images.githubusercontent.com/110280845/193229725-d850f6ae-88c6-4157-8465-3d650deba615.PNG)
> 
> I want to get confirmation that the settings should be like this layout.

@xquanluu We discussed putting the tabs inside the form section similar to how we did on the carrier view. That would be a desirable change since as they are now they look/feel broken or out of place.

**Comment by xquanluu** [comment]
Thanks @kitajchuk sure fixing it now
@davehorton api-server PR created https://github.com/jambonz/jambonz-api-server/pull/65/files

**Comment by xquanluu** [comment]
![service_tab](https://user-images.githubusercontent.com/110280845/193528925-314310c4-bfea-4e92-acaf-a9e73ee4aff9.PNG)
![admin_tabs](https://user-images.githubusercontent.com/110280845/193528928-5c09b342-8e77-4524-b941-9cc47ba8f2a2.PNG)

**Comment by xquanluu** [comment]
I just made this change to the UI, please help to check if this is fine?

**Comment by xquanluu** [comment]
![new_settings](https://user-images.githubusercontent.com/110280845/193536162-c63b10a4-2897-470b-a5b5-f53da0b929d5.PNG)
 Or the Tabs should be like this?

**Comment by kitajchuk** [comment]
> ![new_tabs](https://user-images.githubusercontent.com/110280845/193536303-1fe306d4-436d-4f9e-98d3-c615b99ac367.PNG) ![admin_tabs](https://user-images.githubusercontent.com/110280845/193549534-8ed4d134-b25d-44bd-a2fe-26a02166e71c.PNG)
> 
> Or the Tabs should be like this?

In my prior comment I said “ In this case we can render the tabs right below the first field set with the message about required fields.” That’s what we would like to see here so none of these are doing that 🤔

**Comment by kitajchuk** [comment]
> ha ha, I'm sorry, my bad again...
> ![service_tab](https://user-images.githubusercontent.com/110280845/193593415-799fde54-5b5d-4974-8d8b-fee0c849d88e.PNG)
> ![password_settings](https://user-images.githubusercontent.com/110280845/193593430-27830a3a-4d27-4f09-9e43-5c38559be48d.PNG)
> Is this what you means?

Close but there’s double padding around the tabs. You may have wrapped the tabs in a field set which you don’t need to do. We have some styles that target the UI tabs in the forms already:

https://github.com/jambonz/jambonz-webapp/blob/052ea4d6cb79b2bd55218bfcb738624d28ae471a/src/styles/_forms.scss#L86

And if you look at the carrier form you’ll see we don’t wrap the tabs in a field set:

https://github.com/jambonz/jambonz-webapp/blob/052ea4d6cb79b2bd55218bfcb738624d28ae471a/src/containers/internal/views/carriers/form.tsx#L615

**Comment by xquanluu** [comment]
Thanks a lot @kitajchuk , I fixed it,

here is first draft PR: https://github.com/jambonz/jambonz-webapp/pull/130

It's really great if I can have your review and give comment if there is issue, anti-pattern ..etc in the PR so I can fix it.

**Comment by davehorton** [comment]
@EgleHelms I think all this PR needs is to be rebased off the latest main branch.  Could you do that?  Also, make sure to pull the latest main branch of jambonz-api-server for testing, as I just merged in the API (/PasswordSettings) that this feature uses.
