### ISSUE TITLE
Need additional inputs on Carrier form to support outbound registration

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#135]
Currently, when configuring a carrier that requires registration we have these input fields to complete:

![image](https://user-images.githubusercontent.com/1884973/194271145-199a786d-1e72-44f8-86cd-40d3f3428ef1.png)

Recently, we added a few more options to the database, which allow you to also specify some other settings on the REGISTER requests that will be sent:

- the from user (appears in the sip From header of the REGISTER)
- the from domain (ditto)
- whether to use the public ip in the host of the Contact header, or the sip realm we are registering with

These fields have been added to the database in a recent commit to jambonz-api-server
```
register_from_user VARCHAR(128),
register_from_domain VARBINARY(255),
register_public_ip_in_contact BOOLEAN NOT NULL DEFAULT false,
```

Now we need to add them into the webapp so that users can set them.

- an input field for From username (optional, can be left blank)
- an input field for From domain (optional)
- a checkbox for Use Public IP in Contact (defaults to unchecked)

This needs to be done on both the legacy and the main branch.

**Comment by davehorton** [comment]
I will take this

**Comment by davehorton** [comment]
added in v0.7.7-rc7 on legacy branch, still needs to be added on main branch

**Comment by kitajchuk** [comment]
@davehorton This could be a good ice breaker for the new developer to tackle 🤔

**Comment by davehorton** [comment]
Hi Egle - I might have mentioned that we have two active branches:
- 'legacy' - this is the older branch (which your are probably familiar with), dates from before we did a UI makeover and code cleanup
- 'main' - this is the newer branch that you would mostly be working on

This particular feature (the addition of some new fields on the Carrier panel) I actually did on the legacy branch recently.  But now we need those same fields in the main branch.  Could. you take a look at that?  Please create a branch off the main branch and then make a PR for review.
