### ISSUE TITLE
Feature: admin user should be able to create other admin users

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#141]
The initial admin user should be able to create additional admin-level users.  In order to do so, we need a Users panel that has add/modify/delete capabilities.  I suppose it should follow the style of similar listview/detail panels in the UI such as Accounts, Applications, etc

@kitajchuk initially I was thinking that there could be a new "Users" tab as part of the Settings panel, but now I wonder if it might be simpler to just create a new left-hand side menu item "Users" which is conditionally visible only when the logged-in user has "PROVISION_USERS" permissions, since that is now being returned as part of the /login API.  What do you think?  Is it possible to show or hide a left hand side menu item easily?

Alternatives are we could instead have Users as a tab on the Settings view, or have something like we do in hosted ui on jambonz.us and jambonz.xyz where we have a hamburger menu which gives access to a completely new page for User management.

I kind of think following our current pattern and just making a left-hand side menu might be simplest best.

Regardless, the Users listview should show the following information (in the initial release of this feature, all users are admin users)

- name (this is the username used to login)
- email (this is actually required in the database, currently the initial admin user is being set to a bogus value, need to fix)
- scope (admin, service provider, account)
- permissions (viewonly, manage services, manage users)
- active (true/false)

ADD
An admin user should be able to add another admin user by providing name, email, and an initial password.  The initial password should obey the password_settings requirement as to minimum length etc.  The user account should automatically have force_change set to true so that the new user will be prompted to change their password on first login.

DELETE:

An admin user should be able to delete any of the user accounts with the exception of his or her own, and the initial 'admin' user, which can never be deleted.

EDIT

An admin user should be able to modify the following settings of any user:
- setting force_change to true to force the user to change their password on next login
- to set a user account to inactive (except for the original admin account)

Note: I am assigning @kitajchuk  for review of the issue and @EgleHelms  for implementation

**Comment by davehorton** [comment]
@kitajchuk can you give your thoughts about how/where we should position the Users listview panel in the app?

**Comment by kitajchuk** [comment]
> @kitajchuk can you give your thoughts about how/where we should position the Users listview panel in the app?

I think having a users nav on the left is probably best. So it would need to be in the top list, not the BYO list.

**Comment by EgleHelms** [comment]
@davehorton @kitajchuk  this is the current state:
Users list page:
![image](https://user-images.githubusercontent.com/63853378/200633404-8fff7fb1-b84b-4cb2-9855-f35872ec05a1.png)

I can also make the usersList more like a table, similar to API keys in the Account view. Or do we want to do something completely different from what we already have?

User Edit form:
![image](https://user-images.githubusercontent.com/63853378/200633594-07210fb1-a96d-4593-9725-e9160b57acf3.png)
![image](https://user-images.githubusercontent.com/63853378/200633704-0a1fb9e5-7b2e-40ef-8cf3-d5df94dc308f.png)

I haven't yet addressed the details of permissions (who should be allowed to see what). Unfortunately, es-lint is not allowing me to push my initial changes to a public branch yet, soo many loose ends.

@davehorton I start needing other API calls like 
- GET users/:user_sid
- POST  users/:user_sid
- PUT users/:user_sid
- DELETE users/:user_sid

Shall I make these changes or shall I leave it up to you?

**Comment by davehorton** [comment]
@EgleHelms yes, why dont you create a branch off main in jambonz-api-server and create the api calls that you need there.

**Comment by davehorton** [comment]
> I can also make the usersList more like a table, similar to API keys in the Account view. Or do we want to do something completely different from what we already have?

Yes, I definitely think the users listview needs to be "table-like".  There could be large numbers of them and a table view makes most sense, along with the ability to filiter by:
- admin users only
- users for a service provider (dropdown select of service providers to choose from, show both service provider users as well as account users under the selected service provider
- users for an account (dropdown select of accounts to choose from, given that a service provider has been chosen)

**Comment by davehorton** [comment]
I think there should be a checkbox labeled "Show admin users", when checked the dropdowns for service provider and account are hidden.  When unchecked, the dropdown for service provider is shown and, if a service provider is selected, then dropdown for accounts is shown.  Both of these dropdowns should have a choice "All" to show all service providers or all accounts for a service provider

**Comment by davehorton** [comment]
@EgleHelms when adding a new user, in the add user form we should not see the Delete button

![image](https://user-images.githubusercontent.com/1884973/201370929-aafea2f3-1ea3-4f19-a0ac-2cf22309a526.png)

**Comment by kitajchuk** [comment]
@davehorton @EgleHelms I will review this branch this weekend and provide feedback on UI etc 👍

**Comment by EgleHelms** [comment]
Yeah, I already fixed the delete button when adding the new user :) I also noticed it. 
@davehorton I believe you should be able to delete your own user, why not? Just probably I should log the deleted user out and remove the jwt in the localstorage instead of now it makes no difference since the jwt is valid for an hour. Or do you still think we should not allow the deletion of your own users?

**Comment by kitajchuk** [comment]
@EgleHelms Can you open a Draft PR for this branch for now. I did a quick look at the compare diff for the branch and have plenty of feedback so might be nice to get it open so I can start adding feedback to dial things in :)

**Comment by EgleHelms** [comment]
I already pushed the password check for the temp password.
Just FYI only the search filter is working.

@kitajchuk I think I will need your help with the other filtering (service_provider, account, admin). I was not yet able to figure out how to correctly manage the state of the filters and how to combine the results.

**Comment by EgleHelms** [comment]
> @EgleHelms Can you open a Draft PR for this branch for now. I did a quick look at the compare diff for the branch and have plenty of feedback so might be nice to get it open so I can start adding feedback to dial things in :)

yeah, will do.

**Comment by kitajchuk** [comment]
> I already pushed the password check for the temp password. Just FYI only the search filter is working.
> 
> @kitajchuk I think I will need your help with the other filtering (service_provider, account, admin). I was not yet able to figure out how to correctly manage the state of the filters and how to combine the results.

Sure thing. I’ll take a deeper look this weekend and get feedback in there for you.

**Comment by davehorton** [comment]
> Yeah, I already fixed the delete button when adding the new user :) I also noticed it. @davehorton I believe you should be able to delete your own user, why not? Just probably I should log the deleted user out and remove the jwt in the localstorage instead of now it makes no difference since the jwt is valid for an hour. Or do you still think we should not allow the deletion of your own users?

Hmm, that is a good question I guess.  Perhaps it makes sense, just as you say you must immediately log them out and also make sure they don't delete the last active admin user (I see you already have this check, may need to add a check that it is indeed active so we dont have a state where we have only one admin user but they are inactive)

**Comment by kitajchuk** [comment]
> > Yeah, I already fixed the delete button when adding the new user :) I also noticed it. @davehorton I believe you should be able to delete your own user, why not? Just probably I should log the deleted user out and remove the jwt in the localstorage instead of now it makes no difference since the jwt is valid for an hour. Or do you still think we should not allow the deletion of your own users?
> 
> Hmm, that is a good question I guess. Perhaps it makes sense, just as you say you must immediately log them out and also make sure they don't delete the last active admin user (I see you already have this check, may need to add a check that it is indeed active so we dont have a state where we have only one admin user but they are inactive)

Regardless of safety checks for this on the frontend the backend should also enforce these rules. Does it?

**Comment by davehorton** [comment]
> Regardless of safety checks for this on the frontend the backend should also enforce these rules. Does it?

Good point.  Currently it does not
