### ISSUE TITLE
add support for Nuance as a Speech Provider

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#142]
We are in the process adding support for Nuance as a speech provider, so we need to add them as a choice in the dropdown for the Speech Credentials panel.  When you select Nuance you should be prompted to enter the following credentials:
- client id
- secret

You can select either tts or stt or both.

The list of languages that are supported by Nuance for STT and TTS can be found here:

https://docs.mix.nuance.com/languages/#languages

Also, in case its simpler to copy I have created a json document [here](https://gist.github.com/davehorton/47795673f4014a5422ff7ab3dbc28bfb) with the TTS voices (I dont have one for STT, you will need to copy the information from that web page).

I have not yet added support for Nuance to jambonz-api-server so your attempts to call the POST api will fail, but I will work on that and meanwhile you can work on the UI.

**Comment by davehorton** [comment]
I realize that the data for nuance TTS voices needs to be slightly different than the others.  That is because in addition to language and voice, nuance has a 'model' attribute which can be either 'standard' or 'enhanced'.  So as far as what we will need to save to the database when a user selects a tts voice it will be a tuple of {language, voice, model}.

I will get a better dump of nuance voices to provide the data for the file we will need to create in source/vendor/speech-synthesis/

**Comment by davehorton** [comment]
I've pushed a branch "feature/nuance-speech" which has the types and data for nuance stt and tts.  

@EgleHelms can you pick up and work off this branch?  

First thing will be to get the dropdown working in the Application view so you can select Nuance for either STT and/or TTS and see the appropriate/supported languages and voices.

When showing the voice in the applications panel for a given language, the label in the dropdown should include the name of the voice and whether it is enhanced or standard model, e.g.

"Cloe (standard)"
"Evan (enhanced)"

Second thing will be to add Nuance as a provider in the Speech credentials panel.  Right now, the POST will fail as I have not done the backend work yet, but you should be able to sort out some of the UI stuff in terms of adding Nuance as a choice in the dropdown, and when Nuance is selected collecting a client_id and a secret (both strings).

These two properties we must include in the POST request payload when creating a Nuance speech service, beside the common ones (e.g. use_for_tts, use_for_stt etc).

**Comment by davehorton** [comment]
I've checked in a branch called feature/nuance-speech in the jambonz-api-server repo that attempts to support adding and testing nuance speech credentials.  You can test against this -- I am not sure it works because I have not actually tested it myself, but give it a try

**Comment by EgleHelms** [comment]
@davehorton please check need some feedback: https://github.com/jambonz/jambonz-webapp/pull/144

**Comment by davehorton** [comment]
looks good, merged.
