### ISSUE TITLE
Generating webhook secrets not possible in creation of new account workflow

### ISSUE THREAD

**Issue by jontyk** [jambonz/jambonz-webapp#18]
Generating webhook secrets not possible in creation of new account workflow
Possible to hack around by modifying webapp to send an accountSid of 0 if there is no account sid, then modified the API to still be able to generate a new webhook secret even if the specified account doesn't exist.

See hacky work around:
[api-server.txt](https://github.com/jambonz/jambonz-webapp/files/6990873/api-server.txt)
[webapp.txt](https://github.com/jambonz/jambonz-webapp/files/6990874/webapp.txt)

Cleaner fix would be to either move generation of new ids directly to the add form, or to create new top level endpoint to generate secrets for adding flow.

**Comment by davehorton** [comment]
Please pull the latest jambonz-api-server, which fixes this issue in [this commit](https://github.com/jambonz/jambonz-api-server/commit/ecdf9898f827b356ecde909baddf378ceb8d398f)
