### ISSUE TITLE
Persisting state in between refreshes of the page

### ISSUE THREAD

**Issue by EgleHelms** [jambonz/jambonz-webapp#180]
This is a new feature to be introduced to the webapp to prevent "refresh" resulting in jumping to the default state of the app.

**In two use cases this are very problematic and confusing during real-life use of the app:**
- Service Provider is jumping to the first one in the Array when refreshed. This is especially bothersome when for example waiting for the Recent calls list to update - we refresh to see the updated list, but we see instead we see another Service Provider Resent calls list.
- After redirect done when a new resource creation it can be confusing, since you are redirected to the Resource list, but the filter is not applied to the correct one to see the resource you just created. (It goes back to "all accounts" list)

**Comment by EgleHelms** [comment]
@kitajchuk 
I think actually local.storage would work nicely here, even though it is a simplistic solution, since we do not need to store many values in general. Like a resource ID when creating some new resource (Carrier/Speech/App/...) and when redirecting check it to apply the correct filter. And the Service Provider id in Admin user case, would be stored and checked. So only 2 extra values would need to be stored. And I somehow dont see the complexity of this app growing, maybe just the size (more lists, more resources) still the same two extra values to store in addition to some messages and jwt.

**Comment by davehorton** [comment]
Hi @kitajchuk if you only had time to give us feedback on one thing it would probably @EgleHelms proposed approach here to use local storage.  Realize you are busy, so we will probably move forward with this if we don't hear back
