### ISSUE TITLE
SP delete not working if there is an SP level user

### ISSUE THREAD

**Issue by EgleHelms** [jambonz/jambonz-webapp#197]
Currently, when we try to delete SP, it actually shows what resources need to be deleted to be able to delete the whole SP, however, this was not applied to Users. So when I try to delete SP that has SP level user, it is throwing a DB error.

The check should be added to the normal deletion check for SP.

**Comment by EgleHelms** [comment]
@davehorton  I see that the check for active Accounts is in the jambonz-api-server. Shall we add it in the same place or separate it?

**Comment by EgleHelms** [comment]
Maybe this is a good fix for this: https://github.com/jambonz/jambonz-api-server/pull/104/files

**Comment by davehorton** [comment]
is this still open or was it fixed in the recent pull requests?

**Comment by EgleHelms** [comment]
Fixed :)
