### ISSUE TITLE
add support for nvidia speech

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#199]
We want to add support for Nvidia, which makes a speech product called Riva.  Nvidia supports both STT and TTS.  It is typically deployed on-prem; ie the customer will generally build and run it on their own server rather than use an Nvidia-hosted cloud service (as far as I can tell, there is no such thing).  It appears there is no authentication required to access the APIs, other than the URI (ip:port) at which the Nvidia server is listening for requests over grcp.

The list of languages supported for STT is [here](https://docs.nvidia.com/deeplearning/riva/user-guide/docs/asr/asr-overview.html#language-support), and the list of voices/languages supported for TTS is [here](https://docs.nvidia.com/deeplearning/riva/user-guide/docs/tts/tts-overview.html#voices).

Again, the only "credential" is the uri (ip or dns name colon port).

PR should be opened here, as well as for jambonz-api-server.  (I am already working on the changes to feature-server)

**Comment by xquanluu** [comment]
Thanks @davehorton , start contributing to this.

**Comment by davehorton** [comment]
completed and merged in 0.8.1
