### ISSUE TITLE
Add support for custom speech vendors

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#213]
We want customers to be able to add support for abitrary speech vendors by writing to a common API.  As part of this they need to be able to add speech credentials for custom "vendors" in the webapp.  The following changes are needed:

## Adding a speech credential

There should be a new vendor in the dropdown, labeled "Custom".  Since a user should be able to add multiple custom solutions, and we need to distinguish them by a unique vendor name, when the user selects "Custom" we must then gather a "Name" value from them.  When we POST the new credential we will concatenate them as "Custom" colon Name.

For example, the user selects "Custom".  Then next see the entry form with the "Use for text-to-speech" and "Use for speech-to-text" checkboxes.  Directly below that there should be a required input field labeled "Name".  Below that there should be a second (optional) input field labeled "Auth token".  

Finally, if they select to use for STT there should appear an input field labeled  "STT websocket URL" (if STT is selected, this field is required).  And if they selected to use for TTS there should additionally be an input field labeled "TTS http URL".  Again, use for TTS is selected this field is required.

Let's say the user adds a custom speech vendor for both stt and tts, gives a name of 'allomedia' and provides the other information.  The payload should be submitted to the backend as follows:
```json
{
	"vendor": "custom:allomedia",
	"account_sid": "...",
	"service_provider_sid": "...",
	"use_for_tts": 1,
	"use_for_stt": 1,
        "auth_token": "foobarbazzle",
        "custom_stt_url": "wss://myserver.com:2333",
        "custom_tts_url": "http://tts.myserver.com:80"
}  
```
## Editing a speech credential

In the edit panel we should parse the Name from the vendor value returned from the server; e.g. so that we can show "allomedia" in the Name field when the vendor value returned was "custom:allomedia"

**Comment by davehorton** [comment]
hey @xquanluu I tried to rebase your branch on main, where we have added soniox as an stt vendor, but after resolving merge conflicts it looks like I messed it up, because in the Applications view for TTS vendors when I click the pull down I don't see a custom vendor that I added (I do see it in the STT dropdown).  Could you have a look and try to fix what I got wrong, so that this branch is rebased on main (supports soniox STT) and also supports custom vendors ?

**Comment by xquanluu** [comment]
Yes Sure @davehorton, start working on this

**Comment by xquanluu** [comment]
I fixed it @davehorton

**Comment by xquanluu** [comment]
PR merged, close this issue
