### ISSUE TITLE
Can not add carriers under chrome

### ISSUE THREAD

**Issue by timmeade** [jambonz/jambonz-webapp#214]
Adding Carrier to new aws marketplace.

Upgrade to SSL. per instructions

When adding carrier using Chrome

Version 110.0.5481.177 (Official Build) (arm64)
Nothing happens on save. Console shows:

An invalid form control with name='sip_username' is not focusable. 
<input id="sip_username" name="sip_username" type="text" placeholder="SIP username for authenticating outbound calls" value required>
Tried exact same procedure on safari

Version 16.3 (18614.4.6.1.6)
Works fine.

**Comment by davehorton** [comment]
fixed in 0.8.2
