### ISSUE TITLE
support for Nuance on-prem

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#219]
Nuance speech service can either be accessed via their cloud service -- this is what we support today, and it requires a client id and secret -- or it can be installed on a customer premise.  In the latter case, all we need is the uri, in terms of ip:port (similar to nvidia).

So when adding a speech service for Nuance there should be choice of entering either:
- client and and secret, OR
- uri

We should probably have radio buttons to guide the user labeled:
- "Hosted"
- "On-prem"

**Comment by davehorton** [comment]
This is slightly more complicated than I thought, because when using the on-premise nuance product (which is called Krypton, I believe), you can have different uris for STT and TTS.  For instance:
```
STT : 3.198.234.41:7021
TTS : 3.198.234.41:7023
```
So the full set of credentials that are possible for nuance are:
- client_id (when using hosted)
- secret (when using hosted)
- nuance_tts_uri (when using on prem tts)
- nuance_stt_uri (when using on prem stt)

And the user should be able to mix and match, e,g,
- hosted for both stt and tts (they provide only client_id and secret)
- on prem for both stt and tts (they provide nuance_tts_uri and nuance_stt_uri)
- hosted for stt and on prem for tts (they provide client_id, secret, and nuance_tts_uri)
- on-prem for stt and on hosted for tts (they provide client_id, secret, and nuance_stt_uri)

Currently the nuance panel looks like this:

![image](https://user-images.githubusercontent.com/1884973/227600849-84a91b3b-47b5-4712-abdd-37f9a4f6703f.png)

I suggest we leave the Client ID and Secret inputs as they are, but remove the red asterisk as they are no longer necessarily required.  

Then, below that have a check box labeled "Use on-prem TTS".  To the right of the checkbox should be an input field that is disabled until the checkbox is checked.  Then it is enabled and should have placeholder text "ip:port".  The entry should be validated that it ends with a colon and digits (we should allow them to enter either an IP or a DNS for the host part, so don't validate that part).

Below that, similarly, have a check box labeled "Use on-prem STT".  To the right of the checkbox should be an input field that is disabled until the checkbox is checked.  Similar validation there.

Form-level validation, before submit, they must have either entered client id and secret or entered a uri

**Comment by xquanluu** [comment]
close as PR is merged
