### ISSUE TITLE
show registration status for carriers that require register

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#225]
When defining a carrier that requires jambonz to send outbound registrations the relevant panel looks like this:

![image](https://user-images.githubusercontent.com/1884973/229319630-c3886524-d583-4469-8474-846f7baebfc1.png)

I would like to enhance this view so that under "Use public IP in Contact" there is a label "Registration status:" with a value showing the current status (ie the most recent response to a register request).  So for success it would show:

Registration status: successfully registered (200 OK)

or 

Registration status: failed (408 Request TImeout)

This will require changes in the api-server and also possibly in sbc-sip-sidecar as well

**Comment by davehorton** [comment]
As a further enhancement, it would be nice if the status was a link such that when you click it downloads the pcap for that most recent register request.  This will require us to figure out the proper http request to make to homer

**Comment by xquanluu** [comment]
Start contributing to this.

**Comment by davehorton** [comment]
actually, in thinking about this I think it would be better for the status to be shown on the carrier list, e.g.

![image](https://user-images.githubusercontent.com/1884973/229319775-10b25aef-cb0b-4f2e-818a-2ff7d851c62b.png)

Alongside or next to "active" we could show "registered OK" or "register failed", again each being a link to download a pcap

**Comment by xquanluu** [comment]
Hi @davehorton I finished the work here. Please help to review related PRs:
https://github.com/jambonz/db-helpers/pull/11/files
https://github.com/jambonz/sbc-sip-sidecar/pull/19
https://github.com/jambonz/jambonz-api-server/pull/141
https://github.com/jambonz/jambonz-webapp/pull/226

**Comment by davehorton** [comment]
all looks good, I've merged all but sbc-sip-sidecard which just needs an update to package.json for latest db-helpers

**Comment by xquanluu** [comment]
Closed this issue as it's done
