### ISSUE TITLE
SBC addresses shown are outdated sometimes

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#227]
If an SBC SIP server has had many public IPs in its lifetime, all of them will show in the list even though some of them might no longer be active

![image](https://user-images.githubusercontent.com/1884973/230172102-69909011-ea51-4f1b-b753-7c446c2d5544.png)

We need some way of aging out the older/no longer used one.  I suggest rather than adding the SBC ip once when sbc-sip-sidecar starts, it should perhaps write the record with a timestamp, and periodically (every 15 mins or so) update the timestamp as well as purge any entries that have not been updated in more than an hour (or so).

**Comment by xquanluu** [comment]
start working on this issue.

**Comment by xquanluu** [comment]
@davehorton Here are PRs:
https://github.com/jambonz/sbc-sip-sidecar/pull/21
https://github.com/jambonz/db-helpers/pull/12

**Comment by xquanluu** [comment]
Hi @davehorton please update SQL to add new column in table sbc_addresses name last_updated.

**Comment by xquanluu** [comment]
Closed, PR is merged
