### ISSUE TITLE
tracing UI changes

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#246]
In the tts span the 'cached' property, which should show true or false, is blank

![image](https://user-images.githubusercontent.com/1884973/236889703-9f3e798a-ca38-4f27-84a1-3a0288bbeb07.png)

Please see call placed at 05.08.2023 1:19 PM for example

**Comment by davehorton** [comment]
Also, we need to have an env var which, if set, makes it so we do not show the tracing panel at all in recent calls (i.e., the view should look exactly like those calls for which we do not have a trace_id)

**Comment by davehorton** [comment]
Another issue is that long lines in the detail view are getting truncated.  We need the text to wrap into multiple lines in this case so we can see it all.  Example:

![image](https://user-images.githubusercontent.com/1884973/236899447-3ac366e8-cd0e-4eb2-93b8-1186f5b15b30.png)

**Comment by xquanluu** [comment]
Closed as PR merged
