### ISSUE TITLE
Feature request: Show infrastructure information 

### ISSUE THREAD

**Issue by Megamuch** [jambonz/jambonz-webapp#255]
liKe #228 It would be great to have a summary overview of the Sip RTP and FS ip's, both public and private. 
There are many moving parts and a live overview about different ip's, host names, from the different parts could be really useful

**Comment by davehorton** [comment]
This should be a read-only view in the settings panel for an admin user, probably a new tab labeled "Infrastructure"

**Comment by xquanluu** [comment]
start working on this
