### ISSUE TITLE
Show phone numbers in order on phone number page

### ISSUE THREAD

**Issue by Megamuch** [jambonz/jambonz-webapp#257]
I just noticed that after entering a range of 10 did's on the phone number page, the overview is not in numerical order.

**Comment by xquanluu** [comment]
fixed by this commit in big PR:
https://github.com/jambonz/jambonz-api-server/pull/169/commits/4833a8e48327ecbdfa6c634476ce975ea825e3d2

This PR will fix:
1/ record all call
2/ download pcap for invite and register
3/ phone number in order

**Comment by davehorton** [comment]
@xquanluu can we close?

**Comment by xquanluu** [comment]
No, we cant because this fix is still in on PR for record_all_calls
