### ISSUE TITLE
feature: admin user can clear TTS cache

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#262]
On the Admin settings page there should be the ability to clear / empty the redis cache of all tts prompts.  Presumably this is a button, labeled "Clear TTS Cache".  

It would be nice if there was some text below the button that described the number of cached TTS prompts (presuming a count can be easily retrieved from redis).  So initially, when the admin user arrives on the page the button would be enabled and the text might say "There are 1,248 cached TTS prompts".  If the user then clicks the button to clear the cache, then the text would read "There are 0 cached TTS prompts".  Furthermore the button would be disabled if there are no cached TTS prompts, so after clearing the button would be disabled.  If they come back in later and there are now some cached prompts, then the button would again be enabled

**Comment by davehorton** [comment]
@xquanluu can we close?

**Comment by xquanluu** [comment]
Closing this issue as PR merged
