### ISSUE TITLE
Feature Request: add Recent Calls filtering by phone number

### ISSUE THREAD

**Issue by javibookline** [jambonz/jambonz-webapp#266]
Feature request to have a text input in the "Recent Calls" page to filter calls by from/to fields.

Ideally the match would not need to be exact, neither for the caller nor for the callee number.

It could be implemented, for example, like this

<img width="1081" alt="Captura de pantalla 2023-06-07 a las 16 40 05" src="https://github.com/jambonz/jambonz-webapp/assets/98887695/8de8a24d-be79-48dd-980d-07b4f25b6000">

When there is a substantial number of calls and DDIs, it is very useful to be able to check the calls for a specific number. Same thing applies to checking if an outbound call has been placed for a specific callee. With traces and SIP info, it is even useful for debugging purposes.

**Comment by xquanluu** [comment]
Start working on this
