### ISSUE TITLE
Support filtering recent calls based on callSid and have a single filter entry

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#281]
Currently we have this
![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/da38bd98-75dd-47ce-a753-b0366504d6f9)

which lets us filter on From or To number, but not call sid.  It will be common though to have a user report a call sid that we need to look into.  I would like to see two changes

- replace the two filter boxes with a single one
- when an entry is made, search for *either* from, to, call_sid.  Since call_sid has a characteristic uuid format, it may be simpler to skip the from and to check in that case

**Comment by xquanluu** [comment]
Start working on this

**Comment by xquanluu** [comment]
![Screenshot 2023-06-30 at 11 07 50](https://github.com/jambonz/jambonz-webapp/assets/110280845/5b840abd-794d-44a4-ac9f-7b8a864c3ffa)

**Comment by davehorton** [comment]
Looks good.  I think the placeholder text can just be "Filter".  Maybe we could have one of those info icons that give a popup description ("Filter based on call_sid, called or calling number")

**Comment by xquanluu** [comment]
Due to the layout and css of that html row, it's hard to add tooltip to the filter, it mess up the css for other components.

I have fixed the comments to have Filter in placeholder.

**Comment by xquanluu** [comment]
closed as PR merged
