### ISSUE TITLE
Current Jaeger Trace loading implementation in Recent Calls page hits API rate limit

### ISSUE THREAD

**Issue by javibookline** [jambonz/jambonz-webapp#286]
Due to the current implementation of retrieving Jaeger traces for all calls that are displayed in the Recent Calls page, it happens very often that scrolling through pages results in a rate limit of API requests.

Each retrieval of a Jaeger trace is one API request, and they are all loaded at once on each refresh of a subset of Recent Calls (navigating to a page), so if we display for example Recent Calls in pages of 100 calls, and all of them have Jaeger traces, the webapp automatically launches 100 API requests at the same time to retrieve the traces.

As the trace data is only visible when opening the dropdown of a single call, it could be a better solution to load the jaeger data the first time that a dropdown for a specific call is opened (in the same way that the recently added MP3/WAV recordings and PCAP data are loaded only once the dropdown is opened).

**Comment by xquanluu** [comment]
closing this as PR merged
