### ISSUE TITLE
Hosted: Choose a subdomain is confusing

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#293]
When a new user registers with the hosted platform they need to specify a custom subdomain.  On the old (jambonz.xyz) system it was made clear that this was a subdomain of `sip.jambonz.xyz`:
![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/8df66de7-e699-4f0a-a858-904b6e057ae5)

However, on the newer jambonz.cloud system this is not clear at all.
![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/cd81fc71-db82-4601-936a-d3ec35ff36ac)

"Your name" is not a good placeholder.  In addition, we need to show more clearly, as we do in the first example above, that what the user is doing is to specify a subdomain of (in this case) sip.jambonz.cloud.

Furthermore, the older version had a nice feature where after you had entered 3 keyestrokes, the UI would track each key stroke as you typed and either show a green check if the current entry was available
![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/596b777f-f1d6-4bac-81f7-d3a55b30329b)

Or a red cross if that name was already taken
![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/eb1588fb-b967-41da-9f6b-15c8459bef40)

**Comment by xquanluu** [comment]
closing this issue as PR merged
