### ISSUE TITLE
Hosted: Need to inform user to have carriers send calls to <subdomain>.sip.jambonz.cloud

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#294]
On the previous hosted platform on the Carriers view we had a personalized help message that informed the user how to route calls from their SIP providers to their hosted account:

![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/25b956a5-466d-4e04-b3e4-825ba17a106f)

That is missing in the current hosted version, and we need to bring it back

**Comment by xquanluu** [comment]
<img width="1415" alt="Screenshot 2023-08-02 at 12 54 48" src="https://github.com/jambonz/jambonz-webapp/assets/110280845/32fe6724-a56f-4767-91d3-5f0a17286e81">
