### ISSUE TITLE
Slightly confusing what "Clients" means

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#296]
The feature we have where a user can add sip client credentials currently looks like this:

![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/772fd6a6-5992-44ba-bb18-35331e2ba49c)

I think it is going to be slightly confusing for people, because "client" is quite a generic term.  I would like to see a few changes:
- The left hand nav can stay the same ("Clients"), but the title in the Content view should change to "SIP client credentials"
- "No clients" should change to "No sip clients"
- "Add client" should change to "Add sip client"

Finally, between the title and the filter box I think we should add two lines of descriptive text that read
```
Your sip realm is <realm>.
You can add sip credentials below to allow sip devices to register to this realm and make calls.
```

Note that if the sip realm is not defined for this account, we should instead show one line:
```
You need to associate a sip realm to this account in order to add sip credentials.
```

**Comment by xquanluu** [comment]
closing this as PR is merged
