### ISSUE TITLE
remove some options on credit card payment screen in hosted version

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#297]
In the latest stripe payment details screen it supports payment by credit card or something called "cash app pay"

![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/322bc22b-883a-4b54-a8c2-f217a2773bbc)

Is there a setting where we can not show the "cash app pay" option and only show the card option?

Also, when saving a credit card there is an option to save details for "1-click checkout".  Similarly, I would like to hide this option if there is a setting for that

![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/3547a82c-0584-4adc-b4a7-685adc6b55e1)

**Comment by xquanluu** [comment]
For the options Save your info for secure 1-click checkout with Link , this is controlled by stripe configuration on Stripe portal where you have account, please go to Stripe Link Checkout  settings and change there
