### ISSUE TITLE
update preview description

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#300]
When a link to jambonz is pasted into Slack (and presumably shared via other means) it show a title and a description:

![image](https://github.com/jambonz/jambonz-webapp/assets/1884973/eb2e0873-bfe7-4f45-b14f-e23967ae241d)

The title reads "Jambonz Web App"
The description reads "Simple provisioning webapp for jambonz"

Please change these:
Title should read: "Jambonz Portal | Jambonz CPaaS"
Description should read: "Build innovative voice and collaboration services with jambonz, the open-source communication platform for conversational AI providers and CSPs".

**Comment by xquanluu** [comment]
closing this as PR is merged
