### ISSUE TITLE
Add Azure storage as an option for storing call recordings

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#306]
Currently we support AWS S3 and Google cloud storage.  We should add support for Azure storage as well, possibly using [this npmjs package.](https://www.npmjs.com/package/@azure/storage-blob).

[See also](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction)

**Comment by xquanluu** [comment]
Start working in this

**Comment by xquanluu** [comment]
closing as PRs merged
