### ISSUE TITLE
Feature: add delete button to call recording 

### ISSUE THREAD

**Issue by EgleHelms** [jambonz/jambonz-webapp#308]
Currently, you can only listen and download the recorded file that is stored in the webapp. We would like to have a delete button, that deletes the recording directly in the 3rd party platform that is connected to store the recordings (currently S3 from AWS)

This would be an improvement that allows users to have more control with regard to GDPR regulations.

**Comment by davehorton** [comment]
Good idea.  Do note as well that you can configure policies on the AWS S3 side to automatically delete all files older than X days in the bucket.

**Comment by xquanluu** [comment]
Start working on this.

**Comment by xquanluu** [comment]
Closing this as PR merged
