### ISSUE TITLE
Wrong language value stored for Cobalt when editing existing application

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#325]
To recreate:
- create an application that uses Google for recognition and language English US
- now change the vendor to Cobalt, but leave language as English US

The result is that applications.speech_recognizer_language is set to 'en-US', whereas it should be set to 'en_US-8khz' since the vendor is now Cobalt.

Note: after fixing the bug, make sure the reverse works as well -- if the vendor is then changed back to google and the language dropdown is left at English US the language in the db should then be 'en-US'

**Comment by xquanluu** [comment]
Closing this As PR merged
