### ISSUE TITLE
custom speech engine selection gives blank screen

### ISSUE THREAD

**Issue by vasudevan-Kore** [jambonz/jambonz-webapp#365]
when we select any custom speech engine TTS from the dropdown in any application we encounter a blank screen. The issue is consistent. 

https://www.loom.com/share/46bdb8e5d8e84b54bf79a96ca725ac5c?sid=a06ca783-8850-4e8a-83f9-076a216234f0

**Comment by davehorton** [comment]
fixed in this PR: https://github.com/jambonz/jambonz-webapp/pull/361
