### ISSUE TITLE
Portal ElevenLabs Status

### ISSUE THREAD

**Issue by flean** [jambonz/jambonz-webapp#405]
<img width="1116" alt="Screenshot 2024-02-19 at 12 50 45 PM" src="https://github.com/jambonz/jambonz-webapp/assets/1794772/1899bcb2-e4e6-45df-a6e9-6bdc4cfb74f5">

Portal says Status Fail 

```
https://jambonz.cloud/api/v1/ServiceProviders/undefined/SpeechCredentials

Bad Request 

Response {"msg":"Bad request"}
``` 
Here is proof it is working in apps.

<img width="471" alt="Screenshot 2024-02-19 at 12 52 51 PM" src="https://github.com/jambonz/jambonz-webapp/assets/1794772/8f8838e3-cdfd-4c65-a471-b773f962f01c">

**Comment by xquanluu** [comment]
Hi @flean 
Have your buy your key?  If you are using trial keys, this issue will happens.

By using your key to run this code multiple time, please make sure that the key does not return error.

```
curl --request POST \
  --url https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM \
  --header 'Content-Type: application/json' \
  --header 'xi-api-key: your-key-is-here' \
  --data '{
  "model_id": "eleven_turbo_v2",
  "text": "Hello"
}' -v
```

**Comment by xquanluu** [comment]
it's also strang that https://jambonz.cloud/api/v1/ServiceProviders/undefined/SpeechCredentials

undefined is in url path, could you tell me steps to have this issue, I cannot reproduce it in my jambonz server.

**Comment by flean** [comment]
I sa that error on the speech page, looking at the XHR/Fetch requests. 

I upgraded ElevenLabs to Paid and that fixed the status issue. So, I think you should add that the trial accounts will show status failed but work.
