### ISSUE TITLE
Feature: Streaming Say verb

### ISSUE THREAD

**Issue by flean** [jambonz/jambonz-webapp#407]
Is there a way to add a Streaming Say verb that will work like config with bargein for listening but for sending TTS?

**Comment by davehorton** [comment]
I dont understand what you are asking for.

**Comment by flean** [comment]
I'll clarify, I'd like to be able to stream text to an always open SAY verb. 

It's like the inverse of sticky bargein listening to the user talk and if they talk it hits an actionHook with event speechDetected and streams the text.

I'd like to be able to stream the text response I receive from an LLM Agent stream so it can speak faster.

Currently I created a FIFO queue and after a few words I send them off but there is a hiccup and sometimes the audio gets cut off. I'm not sure why, I've logged it and there is nothing that should be interrupting the last say verb but it gets cut off every now and then.

**Comment by davehorton** [comment]
we have no plans for this, the the upcoming bidirectional audio streaming support in listen verb may do what you want
