### ISSUE TITLE
Todo: Fix webpack issues currently active on the project

### ISSUE THREAD

**Issue by kitajchuk** [jambonz/jambonz-webapp#43]
These issues are present in the webpack pipeline for local dev server and when building for production. They should be easy to fix so I am making an issue here to track so we can do so 👍.

I'm not sure what introduced the `less` files (something in `antd`) but it's a file loader issue and it doesn't look like Create React App supports less loading out of the box...

The ESLint warnings are easy to fix, however.

<img width="898" alt="Screen Shot 2022-02-22 at 7 27 14 PM" src="https://user-images.githubusercontent.com/438711/155257202-64b9589c-5809-4453-9c76-7d5ec79c3279.png">

**Comment by cluzier** [comment]
I was able to clean up the terminal in #50 on branch `aws_regions`.
