### ISSUE TITLE
"The server cannot be reached" after fresh installed

### ISSUE THREAD

**Issue by kishanecosmob** [jambonz/jambonz-webapp#437]
Hi Team,

We have installed Jambonz Building a self-hosted solution with two servers.

Installation was successful and all pm2 are running smoothly.
While logging in to the Jambonz URL with public IP http://103.254.35.50:3001/, we are getting the below error.

I have attached the pm2 logs file from sbc & feature server and screenshot for your reference.

![Screenshot from 2024-06-10 11-53-16](https://github.com/jambonz/jambonz-webapp/assets/96779259/ddd1fe6d-d82e-4389-835e-70aaccb502fa)
![Screenshot from 2024-06-10 11-52-21](https://github.com/jambonz/jambonz-webapp/assets/96779259/eb90054c-0b60-4c02-9a8a-24e1c1c22371)
![Screenshot from 2024-06-10 11-50-34](https://github.com/jambonz/jambonz-webapp/assets/96779259/2ddcc58a-17aa-4e49-8374-15c6364a1380)
[jambonz feature error.docx](https://github.com/user-attachments/files/15766237/jambonz.feature.error.docx)
[jambonz api error.docx](https://github.com/user-attachments/files/15766238/jambonz.api.error.docx)

**Comment by davehorton** [comment]
what is in the .env file in the jambonz-webapp folder?  If its not correct, fix it then run
```
npm run build && pm2 restart jambonz-webapp
```

**Comment by kishanecosmob** [comment]
Hi @davehorton, 

FYI, I have created two servers for SBC and Feature. Both are in a local environment, but I have mapped a public IP to the SBC server and allowed the required ports.

I have attached the .env and ecosystem.config.js files for your reference.

Local server IPs:
SBC: 172.16.16.133
Feature: 172.16.16.134

Please check both files and provide a resolution so that we can access Jambonz and start using it.
Also attached influxd service screenshot if any issues in this let me know.
Thanks in advance.

[ecosystem.config.docx](https://github.com/user-attachments/files/15782332/ecosystem.config.docx)
[jambonz .env file.docx](https://github.com/user-attachments/files/15782333/jambonz.env.file.docx)
![Screenshot from 2024-06-11 10-10-59](https://github.com/jambonz/jambonz-webapp/assets/96779259/3d1b7d7e-c665-4c9e-abef-81e4616b1d08)

**Comment by kishanecosmob** [comment]
@davehorton Also attached log file when i run the reset_admin_password.js file getting the error.

![Screenshot from 2024-06-11 10-13-35](https://github.com/jambonz/jambonz-webapp/assets/96779259/11260872-7c5f-4b25-bb1b-7011c479e021)
[reset_admin_password.js.docx](https://github.com/user-attachments/files/15782377/reset_admin_password.js.docx)

**Comment by kishanecosmob** [comment]
Hi @davehorton 

Please provide me resolution on the above issues. We need to start using Jambonz.
Thanks in advance.

**Comment by davehorton** [comment]
support for clustered environments requires a paid support subscription.  You seem to have created some sort of custom environment and we do not offer a service where we troubleshoot custom setups for free.
