### ISSUE TITLE
"Choose File" button hidden on FF 98.01

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#44]
When trying to upload a google speech json file using Firefox, the "Choose File" button is hidden for some reason

![image](https://user-images.githubusercontent.com/1884973/159478372-394eb675-9117-4092-8a01-4590ae21bc08.png)

**Comment by cluzier** [comment]
This seems to be an issue with Firefox browser version. 
Seems to be displaying the button on a newer version (currently running: 99.0.1)

Possible fix: display some sort of notification when viewing the web-app on Firefox version < 99.0.1 to tell the user that there may be issues viewing the app using their version of Firefox or to suggest updating their Firefox version.
