### ISSUE TITLE
Add support for setting a SIPREC application at the account level

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-webapp#66]
We want to make change to the Add/Edit account panel to allow setting a new variable.  Currently, the panel looks like this:

![image](https://user-images.githubusercontent.com/1884973/182626897-158554af-8d1d-4816-b673-edd0aa01f15b.png)

What we want to do is add a new field right below "Application for SIP Device Calls".

In fact, we want it to be very similar.  It will be a field just like that one, which will show the same dropdown list of applications and let the user choose one.  The label should read "Application for SIPREC Calls"

In the POST or PUT to the API, include the application sid identifier in a property named "siprec_hook_sid"

**Comment by davehorton** [comment]
Also can yo make this UI change?  Right align the dropdown for "Application for SIP Device Calls" and then put the label on one line instead of two lines.  And please do the same with the new label and dropdown

**Comment by khanghugo** [comment]
Got it.
