### ISSUE TITLE
Refresh: Carriers view

### ISSUE THREAD

**Issue by kitajchuk** [jambonz/jambonz-webapp#71]
Implement functional parity for the `Carriers` view form with the new UI style.

Create a branch from `refresh` called `refresh-carriers` and submit a PR to the `refresh` branch. Please include this issue number (`#71`) in the commit/PR message.

You can find the container stub for this view [here](https://github.com/jambonz/jambonz-webapp/tree/refresh/src/containers/internal/views/carriers).

- [ ] The add/edit flow needs to have functional parity with current web app
- [ ] The list view also needs to include the accounts filter functionality

New routes to be added:

- `/internal/carriers/add`
- `/internal/carriers/voip_carrier_sid/edit`

For any questions about design/UI/coding ping @kitajchuk.

Ultimately, when merging PRs, please always use "Squash and Merge" for the strategy.

**Comment by kitajchuk** [comment]
@khanghugo I've merged the MS Teams Tenants and the Phone Numbers PRs. They were looking/feeling good so we can be done with those. This form is up next. I'd like to work out the UI styling for tabs but I don't want that to hold you up on getting started since this is a big form. Go ahead and get started knowing that we're going to have to implement some new UI styling and semantics for the tabs, the gateways fields layouts and the IP whitelist layout. I don't think we need the Chip for SMPP gateways so we can just use a regular checkbox for that. So I'll let you get started and once you have the functionality in place lets connect and I can start getting some UI cleanup going on 👍

**Comment by khanghugo** [comment]
Sure, I will have this one then.

**Comment by kitajchuk** [comment]
@khanghugo I've decided to add the tabs to the `jambonz-ui` library so I have a PR up for that and there is a preview of the storybook deploy on Vercel:

PR: https://github.com/jambonz/jambonz-ui/pull/5
Preview: https://jambonz-ui-git-feature-tabs-jambonz.vercel.app/?path=/story/jambonz-ui-tabs--tabs-menu

This should be nice to use on the Carrier form 👍

**Comment by khanghugo** [comment]
0.0.18 is not up on the registry. I guess I can do something else to have it.

**Comment by kitajchuk** [comment]
> ~0.0.18 is not up on the registry. I guess I can do something else to have it.~ I thought it was merged. Whoops.

Heh, ya, not yet. I'm going to tweak a few more things and then get it merged and published.

**Comment by kitajchuk** [comment]
@khanghugo Okay version `0.0.18` is published. I added a `setActiveTab` prop to the main `Tabs` component which should provide enough utility to the Parent component for knowing which tab is active.

NPM: https://www.npmjs.com/package/jambonz-ui
Storybook docs: https://jambonz-ui.vercel.app/?path=/docs/jambonz-ui-tabs--tabs-menu

**Comment by khanghugo** [comment]
:+1:
