### ISSUE TITLE
Refresh: Speech Services view

### ISSUE THREAD

**Issue by kitajchuk** [jambonz/jambonz-webapp#72]
Implement functional parity for the `Speech Services` view form with the new UI style.

Create a branch from `refresh` called `refresh-speech-services` and submit a PR to the `refresh` branch. Please include this issue number (`#72`) in the commit/PR message.

You can find the container stub for this view [here](https://github.com/jambonz/jambonz-webapp/tree/refresh/src/containers/internal/views/speech-services). It already has the `vendor` select menu logic implemented which can be used for the form. The list view also needs to include the "Used by" accounts filter functionality.

New routes to be added:

- `/internal/speech-services/add`
- `/internal/speech-services/speech_service_sid/edit`

For any questions about design/UI/coding ping @kitajchuk.

Ultimately, when merging PRs, please always use "Squash and Merge" for the strategy.

**Comment by kitajchuk** [comment]
@khanghugo You will notice on this form that I prepped the vendor region selectors for Microsoft and AWS since I did this at the same time I did the speech stuff on the application view ahead of time. I also pre-built a generic file upload component since we need this for the google service key option. You will find a sample google service key JSON file in the `./server` directory of the project that you can use to upload and validate posting.

**Comment by khanghugo** [comment]
Sure, this is getting way quicker. I think I can get one functional one by the end of the day, or maybe morning tomorrow. And for this time, I do double check a lot for parity.
