### ISSUE TITLE
Refresh: Recent Calls view

### ISSUE THREAD

**Issue by kitajchuk** [jambonz/jambonz-webapp#75]
Implement functional parity for the `Recent Calls` view form with the new UI style.

Create a branch from `refresh` called `refresh-recent-calls` and submit a PR to the `refresh` branch. Please include this issue number (`#75`) in the commit/PR message.

You can find the container stub for this view [here](https://github.com/jambonz/jambonz-webapp/tree/refresh/src/containers/internal/views/recent-calls). It already has some info and the logic stubbed for using mock data from a local dev server API implementation.

For any questions about design/UI/coding ping @kitajchuk.

Ultimately, when merging PRs, please always use "Squash and Merge" for the strategy.

**Comment by khanghugo** [comment]
How would you like to proceed with these? At best I can make it have all the functionalities but I don't think I can just test them out.

**Comment by kitajchuk** [comment]
> How would you like to proceed with these? At best I can make it have all the functionalities but I don't think I can just test them out.

Ideally we can work with @davehorton to get the dev db seeded with a robust enough data set for this and alerts so we can properly build and test all filters 🤔. Dave and I have spoken about this a bit already so it’s definitely on his radar. This is all we have left so we can prioritize how to go about this.

**Comment by kitajchuk** [comment]
@khanghugo I finished a functional local dev server with responses for Recent Calls so you can get started using that. It's fully supportive for the UI and I've tested even with the old web app (replacing the axios URLs with our dev server ones) and it's fully functional for that UI 👍. You should be able to build the UI with feature parity using this so give it a shot and just reach out with questions or if you need help. We can probably do this with the Alerts view as well and this should be good enough for local dev with these views.

Commit: https://github.com/jambonz/jambonz-webapp/pull/64/commits/3012bbb7b3c7225a58c544325104c5aa02d074bc

How I changed the axios URLs in the old web app to verify full functionality of the dev server:

<img width="444" alt="Screen Shot 2022-09-01 at 4 51 00 PM" src="https://user-images.githubusercontent.com/438711/188033519-a9aa1c51-2cf6-4050-8cd4-e943a3c4e3ae.png">

As you can see it works just fine so it should be enough to build the new UI:

<img width="1494" alt="Screen Shot 2022-09-01 at 5 20 49 PM" src="https://user-images.githubusercontent.com/438711/188033615-710f3fd9-6fa7-48d4-9b6d-6cc15e36dc64.png">
