### ISSUE TITLE
Recent call view shows no data if refreshed data has not enough data to fill up to the currently selected page

### ISSUE THREAD

**Issue by khanghugo** [jambonz/jambonz-webapp#98]
This is a quick fix. I have it implemented in the alert view. We have to set the current page to 1 if we intend to change some of the filter. The payload's "page" value will stay the same if we don't do that, which there isn't enough page and the backend will return nothing.

In order to reproduce this, have 25/page filter, go to the latest page number, select higher per page filter value, it will return nothing.

This should be added to the thing.
```
  useEffect(() => {
    setPageNumber(1);
  }, [perPageFilter]);
```

**Comment by khanghugo** [comment]
@kitajchuk

**Comment by kitajchuk** [comment]
> useEffect(() => {
>     setPageNumber(1);
>   }, [perPageFilter]);

@khanghugo There's a flash of "No data" on recent calls when you do it that way and also have `perPageFilter` as a dep on the other `useEffect`. I'll push a fix on recent calls but I remove the `perPageFilter` from the other effect and added an `handleSelect` prop to the `SelectFilter` component so the call to `setPageNumber(1)` can be done there.
